
/****** Object:  Table [dbo].[Report_HTML_Params]    Script Date: 05.01.2022 11:06:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Report_HTML_Params](
	[paramID] [int] IDENTITY(1,1) NOT NULL,
	[reportID] [int] NOT NULL,
	[paramName] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[paramID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Report_HTML_Params]  WITH CHECK ADD  CONSTRAINT [FK_ReportID] FOREIGN KEY([reportID])
REFERENCES [dbo].[Report_HTMLS] ([ID])
GO

ALTER TABLE [dbo].[Report_HTML_Params] CHECK CONSTRAINT [FK_ReportID]
GO


